language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: libssh
      before_install: brew upgrade libssh
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssh-dev

before_install:
  - cat -n /Users/travis/.travis/functions
