language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: osx
      brew_packages: libssh
      before_install: brew upgrade libssh && cat /Users/travis/.travis/functions
    - os: osx
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssh-dev
