language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: libssh
      before_install: brew upgrade libssh
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      r_check_args: ""
    - os: osx
      r: 3.6
      r_check_args:
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
    - libssh-dev
